---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

General notes - settings: tools, project options, markdown --\> column
and true i de nederste to drop down

```{r setup}
library(tidyverse)
library(targets)
tar_config_set(store = here::here("_targets")) # telling where the target is stored
source(here::here("R/functions.R"))
lipidomics <- tar_read(lipidomics)
```

## Making a table

shortcut to find names: colnames("dataset")

```{r}
lipidomics |>
  group_by(metabolite) |>
  summarise(across(value, list(mean = mean, sd = sd))) |>
  mutate(across(where(is.numeric), \(x) round(x, digits = 1))) |> # runder alle numereiske værdier til 1 decimal
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) |> # sætter de to sammen i én værdi i tabellen og parenteserne er for at få sd i en parentes
  select(Metabolite = metabolite, "Mean SD" = MeanSD) # "nyt navn = col i data", man vælger i select det, der skal være output i tabellen
```

## function to create table1

```{r}
# Function creating a meanSD outout. The two variables wpcified is the dataset and group_by. Need the "value" column to be generic cause "value" is
create_table_descriptive_stats(lipidomics, metabolite)
```

## Result: basic stats table

```{r}
tar_read(table_descriptive_stats) |>
  knitr::kable(
    caption = "The mean and SD of metabolites in the lipidomics dataset."
  )
```

## plot of distribution

Histogram

```{r}
ggplot2::ggplot(
  lipidomics,
  ggplot2::aes(x = value)
) +
  geom_histogram() +
  facet_wrap(vars(metabolite), scales = "free") + # free: for each it can define its own axis values. facetwrap is the one we want to "group:by"
  theme_minimal()
```

## Making the histogram into a function

```{r}


# Use it like, which should give the same output as before.
create_plot_distributions(lipidomics, metabolite)

```

## Results: Distribution plot

```{r}

tar_read(plot_distributions)

```
